name: rCore
version: ${project.version}
main: niklas.main
author: Niklas
api-version: 1.13
commands:
  tp:
    description: Teleport
  tpall:
    description: Teleport all players to you
  getip:
    description: Get players ip addres
  broadcast:
    description: Send message to everyone
  fly:
    description: enables fly :)
  heal:
    description: Heal yourself and others
  gm:
    description: change your gamemode

